[package]
name = "epoch_of_elria"
version = "0.1.0"
edition = "2021"
authors = ["xingxerx <xingxer@gmail.com>"]
description = "A simple 3D game engine ported from C++ to Rust"
license = "MIT"

[dependencies]
kiss3d = "0.35"